L@cces/src/Lacces/LaccesBundle/Entity/Forms/Form.php
<?php

namespace Lacces\LaccesBundle\Entity\Forms;

use Symfony\Component\Validator\Constraints as Assert;

class Form
{
    /**
     * @Assert\NotBlank
     */
    protected $nom;

    /**
     * @Assert\NotBlank
     */
    protected $prenom;

    /**
     * @Assert\NotBlank
     */
    protected $message;

    /**
     * @Assert\NotBlank
     */
    protected $Email;

    /**
     * @return mixed
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * @param mixed $prenom
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;
    }

    /**
     * @return mixed
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @param mixed $message
     */
    public function setMessage($message)
    {
        $this->message = $message;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->Email;
    }

    /**
     * @param mixed $adresse
     */
    public function setEmail($adresse)
    {
        $this->Email = $adresse;
    }

    public function getNom()
    {
        return $this->nom;
    }

    public function setNom($nom)
    {
        $this->nom = $nom;
    }



    }

L@cces/src/Lacces/LaccesBundle/Controller/AdministrationController.php
<?php

namespace Lacces\LaccesBundle\Controller;

use Lacces\LaccesBundle\Entity\Forms\LogoType;
use Lacces\LaccesBundle\Entity\Forms\userType;
use Lacces\LaccesBundle\Entity\user;
use Lacces\LaccesBundle\Service\FileUploader;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @IsGranted("ROLE_ADMIN")
 */
class AdministrationController extends Controller
{
  public function adminAction(Request $request, FileUploader $fileUploader)
  {
    $em = $this->getDoctrine()->getManager();

    $users = $em->getRepository('LaccesBundle:user')->findAll();

    return $this->render("@Lacces/Administration/administration.html.twig", [
        'users' => $users
    ]);
  }

  public function addAdminAction(Request $request, UserPasswordEncoderInterface $encoder) {

    $em = $this->getDoctrine()->getManager();

    $newAdmin = new user();

    $form = $this->createForm(userType::class, $newAdmin);
    $form->add('submit', SubmitType::class, array(
      'label' => 'Ajouter',
      'attr' => array(
        'class' => "btn btn-hover background-color-orange-lacces waves-effect",
      )));

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {

      $formulaire = $form->getData();
      $this->addFlash('info', "L'administrateur a bien été créé !");

      $newAdmin->setUsername($formulaire->getUsername());
      $newAdmin->setPassword($encoder->encodePassword($newAdmin, $formulaire->getPassword()));
      $newAdmin->setRoles("ROLE_ADMIN");

      $em->persist($newAdmin);
      $em->flush();

      return $this->redirectToRoute('administration');

    }
    return $this->render("@Lacces/Administration/ajoutAdmin.html.twig", array(
      'form' => $form->createView(),
    ));
  }

    public function helpAdminAction (){
        $em = $this->getDoctrine()->getManager();
        return $this->render("@Lacces/Administration/Help/helpAdmin.html.twig");
    }
}

L@cces/src/Lacces/LaccesBundle/Resources/views/Administration/administration.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>L@cces - {% block title %}Administration{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{{ asset('css/jquery_materialize/materialize.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/css_for_views/base/base.css') }}">
    <link rel="stylesheet" href="{{ asset('css/css_for_views/administration/base.css') }}">
    {% block stylesheets %}

    {% endblock %}

    <script src="{{ asset('js/jquery_materialize/jquery.js') }}"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="theme-color" content="#212121">

    <link rel="icon" type="image/x-icon" href="{{ asset('logo_lacces_ico.ico') }}"/>
</head>
<body class="grey lighten-5">
<div class="navbar-fixed">
    <nav class="nav-wrapper grey darken-4">
        <ul class="left">
            <li>
                <a class="sidenav-trigger show-on-large" data-target="slide-out">
                    <i class="material-icons white-text">menu</i>
                </a>
            </li>
        </ul>
        <div id="container_logo_lacces">
            <a href="{{ asset('administration') }}" class="brand-logo center">
                <img id="logo_lacces" alt="Logo L@cces" src={{ asset('pictures/logo/logo_lacces.png') }}/>
            </a>
        </div>
        <ul class="right">
            <li>
                <a class="dropdown-trigger material-icons-dropdown" data-target="dropdown-menu">
                    <i class="material-icons white-text ">more_vert</i>
                </a>
            </li>
        </ul>
    </nav>
    <ul id='dropdown-menu' class='dropdown-content'>
        <li>
            <a class="btn waves-effect background-color-orange-lacces white-text center btn-log"
               href="{{ path('lacces_homepage') }}">
                Lacces
            </a>
        </li>
        <li class="divider" tabindex="-1"></li>
        <li>
            <a class="btn waves-effect background-color-violet-lacces white-text center btn-log"
               href="{{ path('logout') }}">
                Déconnexion
            </a>
        </li>
    </ul>
</div>

<ul class="sidenav grey darken-4" id="slide-out">
    <li class="sidenav-close">
        <a class="sidenav-close waves-effect waves-light">
            <i class="material-icons white-text">arrow_back</i>
        </a>
    </li>
    {% if app.request.attributes.get('_route') == 'administration' %}
    <li class="bold active active-item-menu background-color-violet-lacces">
    {% else %}
    <li class="bold">
        {% endif %}
        <a class="waves-effect waves-light" href="{{ asset('administration') }}">Accueil</a>
    </li>
    {% if app.request.attributes.get('_route') == 'add_admin' %}
    <li class="active active-item-menu background-color-violet-lacces" id="liImg">
        {% else %}
    <li class="grey darken-4" id="liImg">
        {% endif %}
        <a class="waves-effect waves-light" href="{{ asset('/administration/addAdmin') }}">
            Ajouter un administrateur
        </a>
    </li>
    <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
            <li>
                <a class="collapsible-header waves-effect waves-light" id="collapsible-header-click">
                    Gestion des mots
                    <i class="material-icons white-text right" id="material-icons_arrow_drop_down">arrow_drop_down</i>
                </a>
                <div class="collapsible-body">
                    <ul>
                        {% if app.request.attributes.get('_route') == 'lacces_editData_add' %}
                        <li class="active active-item-menu background-color-violet-lacces">
                    {% else %}
                        <li class="grey darken-4">
                            {% endif %}
                            <a class="waves-effect waves-light" href="{{ asset('administration/editData/add') }}">Ajouter un mot</a>
                        </li>
                        {% if app.request.attributes.get('_route') == 'lacces_wordList' %}
                        <li class="active active-item-menu background-color-violet-lacces" id="liImg">
                            {% else %}
                        <li class="grey darken-4" id="liImg">
                            {% endif %}
                            <a class="waves-effect waves-light" href="{{ asset('administration/editData/wordList/fr') }}">
                                Editer les mots
                            </a>
                        </li>
                        <li>
                            <div class="divider"></div>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </li>
    <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
            <li>
                <a class="collapsible-header waves-effect waves-light" id="collapsible-header-click">
                    Gestion des exercices
                    <i class="material-icons white-text right" id="material-icons_arrow_drop_down">arrow_drop_down</i>
                </a>
                <div class="collapsible-body">
                    <ul>
                        {% if app.request.attributes.get('_route') == 'lacces_ex__fr_add' %}
                        <li class="active active-item-menu background-color-violet-lacces">
                    {% else %}
                        <li class="grey darken-4">
                            {% endif %}
                            <a class="waves-effect waves-light" href="{{ path('lacces_ex__fr_add') }}">Ajouter un exercice</a>
                        </li>
                        {% if app.request.attributes.get('_route') == 'listExerciceFr' %}
                        <li class="active active-item-menu background-color-violet-lacces" id="liImg">
                            {% else %}
                        <li class="grey darken-4" id="liImg">
                            {% endif %}
                            <a class="waves-effect waves-light" href="{{ asset('/administration/exercice/listExerciceFr') }}">
                                Editer les exercices
                            </a>
                        </li>
                        <li>
                            <div class="divider"></div>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </li>
    {% if app.request.attributes.get('_route') == 'lacces_helpAdmin' %}
    <li class="active active-item-menu background-color-violet-lacces" id="liImg">
        {% else %}
    <li class="grey darken-4" id="liImg">
        {% endif %}
        <a class="waves-effect waves-light" href="{{ asset('/administration/help') }}">
            Aide
        </a>
    </li>
</ul>

<noscript class="background-color-orange-lacces white-text center flow-text">
    <div class="container">
        <div class="row">
            <div class="col s2 m2 x2">
                <i class="material-icons">warning</i>
            </div>
            <div class="col s10 m10 x10">
                <p>
                    Javascript doit être activé pour une utilisation optimal de l'application !
                </p>
            </div>
        </div>
    </div>
</noscript>

{% block body %}

    {% block message_flash %}
        {% for msg in app.session.flashBag.get('info') %}
            <div class="message-flash background-color-orange-lacces">
                <p>{{ msg }}</p>
            </div>
        {% endfor %}
    {% endblock %}

    <div class="row">
        <div class="col s12 m6">
            <section class="card">
                <span class="card-title center">Administrateurs</span>
                <div class="card-content">
                    <table class="responsive-table striped">
                        <thead>
                        <tr>
                            <th>Administrateur</th>
                            <th>Email</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td>
                                    {{ user.username }}
                                </td>
                                <td>
                                    {{ user.email }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-action">
                    <a id="btn-ajout-admin" class="btn btn-hover background-color-orange-lacces waves-effect" href="{{ path("add_admin") }}">Ajouter un administrateur</a>
                </div>
            </section>
        </div>
    </div>
{% endblock %}
</body>
<script src="{{ asset('js/jquery_materialize/materialize.min.js') }}"></script>
<script src="{{ asset('js/js_for_views/base.js') }}"></script>
{% block javascripts %}
{% endblock %}
</html>

L@cces/src/Lacces/LaccesBundle/Resources/views/Administration/ajoutAdmin.html.twig
{% extends '@Lacces/Administration/administration.html.twig' %}

{% block title %}Ajouter un admin{% endblock %}

{% block body %}

    <div class="container-body">

        {% block message_flash %}
            {% for msg in app.session.flashBag.get('info') %}
                <div class="message-flash background-color-orange-lacces">
                    <p>{{ msg }}</p>
                </div>
            {% endfor %}
        {% endblock %}


        <main>
            <div class="container">
                <div class="container-main-flex">
                    <section>
                        <h2 class="center">Ajouter un administrateur</h2>
                        {{ include('@Lacces/formAddAdmin.html.twig') }}
                    </section>
                </div>
            </div>
        </main>
    </div>


{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/js_for_views/ajoutAdmin.js') }}"></script>
{% endblock %}